<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>ApexMapper.Input</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ApexMapper.Core\ApexMapper.Core.csproj" />
    <ProjectReference Include="..\ApexMapper.Input.Abstractions\ApexMapper.Input.Abstractions.csproj" />
    <ProjectReference Include="..\ApexMapper.Persistence\ApexMapper.Persistence.csproj" />
  </ItemGroup>
</Project>
