<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>ApexMapper.App</RootNamespace>
    <AssemblyName>ApexAnalogMapper</AssemblyName>
    <StartupObject>ApexMapper.App.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ApexMapper.Windows\ApexMapper.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ApexMapper.App.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WPF-UI" />
    <PackageReference Include="Velopack" />
  </ItemGroup>
</Project>
