<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>ApexMapper.Output</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MessagePack" />
    <PackageReference Include="Nefarius.ViGEm.Client" />
    <PackageReference Include="System.IO.Pipes.AccessControl" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ApexMapper.Core\ApexMapper.Core.csproj" />
    <ProjectReference Include="..\ApexMapper.Logging\ApexMapper.Logging.csproj" />
  </ItemGroup>
</Project>
