<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ApexMapper.Core\ApexMapper.Core.csproj" />
    <ProjectReference Include="..\ApexMapper.Logging\ApexMapper.Logging.csproj" />
    <ProjectReference Include="..\ApexMapper.Persistence\ApexMapper.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Adapters\steelseries-apex-pro-v2.json">
      <LogicalName>ApexMapper.Input.Abstractions.adapters.steelseries-apex-pro-v2.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
